### ISSUE TITLE
Inconsitent php syntax highlighting in Chrome

### ISSUE THREAD

**Issue by bjorntheart** [AndiDittrich/WordPress.Enlighter#11]
I've noticed inconsistent php syntax highlighting in Chrome. I am using the latest version. The build details are ```Version 43.0.2357.134 (64-bit)```.

You can find the code here http://bjorntheart.com/2015/07/22/validation-rules-based-on-the-request-method

**Comment by AndiDittrich** [comment]
Dear Bjorn,

there are some rendering issues related to the old tokenizer engine. therefore i've create a new engine which is included within EnlighterJS v2.7 - i will update the Enligher WordPress Plugin as soon as possible

**Comment by AndiDittrich** [comment]
Enlighter v2.8 is out including a new PHP Rendering Engine and a new Tokenizer - this should solve your issue :)

**Comment by bjorntheart** [comment]
@AndiDittrich Great work! That fixed it :-)
