### ISSUE TITLE
Cannot use object of type stdClass as array Line 100, 124 at /enlighter/class/TinyMCE.php

### ISSUE THREAD

**Issue by esumit** [AndiDittrich/WordPress.Enlighter#12]
I have just download your plugin to experiment with my new wordpress based blog, and found the following error : 

Cannot use object of type stdClass as array Line 100, 124 at /enlighter/class/TinyMCE.php

What I did ?, I just commented the code on line 100 and then on 124.

May you please check the issue and let me know your comments,

**Comment by AndiDittrich** [comment]
Dear esumit,

thank's for you report. i can confirm the issue - it only affects users which are using other TinyMCE plugins. to fix it, please change line 72 of  /enlighter/class/TinyMCE.php
**from**
```php
$styles = json_decode($tinyMceConfigData['style_formats']);
```

**to**
```php
$styles = json_decode($tinyMceConfigData['style_formats'], true);
```

the fix will be included within the next release.
best regards, Andi

**Comment by esumit** [comment]
Thanks Andi , appreciate your support and thanks for the awesome plugin.

'Sumit

**Comment by esumit** [comment]
Thanks Andi, :-)
