### ISSUE TITLE
Cannot use the word 'String' within double-quotes for Java

### ISSUE THREAD

**Issue by dan-j** [AndiDittrich/WordPress.Enlighter#13]
I have the following text in my post:

    [java]String str = "A String";[/java]

It renders the following:

    String str = "A String"String";

It seems the above example is matching as a string and as a keyword. The HTML looks like the following:

    <code data-enlighter-language="java" class="EnlighterJSRAW">String str = &quot;Inline String&quot;;</code>

And the DOM is being rendered:

    <span class="beyondEnlighterJS EnlighterJS">
        <span class="kw2">String</span>
        <span class> str = </span>
        <span class="str">"Inline String"</span>
        <span class="kw2">String</span>
        <span class=>";</span>
    </span>

I've also verified that the above behaviour occurs if the string is, "A void" (another java keyword).

Hope the above is enough information. It seems like keywords are still being searched even within quotes.

**Comment by AndiDittrich** [comment]
Dear dan,
thanks for your report!
the bug is already known and related to the EnlighterJS Tokenizer Engine: https://github.com/AndiDittrich/EnlighterJS/issues/8

A Bugfix release will follow asap!

best regaards, Andi

**Comment by dan-j** [comment]
Awesome! I was just looking into how to fix this, cheers for the quick response, it would have been a waste of my time otherwise :)

Cheers
