### ISSUE TITLE
Semi-colons not rendering in both inline and block statements

### ISSUE THREAD

**Issue by dan-j** [AndiDittrich/WordPress.Enlighter#15]
I am using v2.8 of the wordpress plugin and have dropped in the latest version of EnlighterJS, v2.8 (I noticed the plugin was still using EnlighterJS v2.7). The examples below are all using `lang="java"` however I have verified the same also happens for `lang="php"`

The following snippets aren't rendering the final semi-colon.

```
This is an [java]"inline";[/java] string.
```

```
[java]
"string";

[/java]
```

The following does seem to work, so it seems to only occur if the semi-colon is the last character. Spaces and tabs (but not newlines) causes the semi-colon to print.

```
This is an [java]"inline;" [/java] string.
```
```
[java]
"string";
a
[/java]
```

Hope this helps. If you have ideas where the issue is I can have a look at fixing it.

**Comment by AndiDittrich** [comment]
Dear dan-j,
thanks for your report.

i can only reproduce this behaviour using inline code - it works fine on codeblocks.
do you have an example/demo page which shows the issue ?

**Comment by dan-j** [comment]
I'm currently just creating a Wordpress site locally that I'm not hosting yet. I'll look into it again tonight and see if I can get an example somewhere.

Cheers

**Comment by AndiDittrich** [comment]
i've localized the issue: It's an (hopefully final) bug within the EnlighterJS Tokenizer Engine. 
It only appears on a single "non-token" character as last element.
 
i will fix it with EnlighterJS v2.8.1 in the next hours

**Comment by dan-j** [comment]
Ah that's good. Look forward to seeing it.

**Comment by AndiDittrich** [comment]
EnlighterJS v2.9.0 is out including the fix - i'm currently woriking on the WordPress plugin to update it asap

**Comment by AndiDittrich** [comment]
Enlighter 2.9 for WordPress has been released including the fix.
