### ISSUE TITLE
Scripts are always added to head

### ISSUE THREAD

**Issue by Pyknic** [AndiDittrich/WordPress.Enlighter#17]
To improve the loading time of a blog it would be good to be able to control if scripts should be added to the "head" or the "footer" part of a wordpress theme. There is an option in the admin panel for controlling where the initalization script should be placed (`jsType`), but it does not affect other scripts.

Two ways to solve this would be to either add an additional option in the admin panel or to let `jsType` control the location of all the scripts.

**Comment by AndiDittrich** [comment]
Dear Pyknic,

it's a good idea but i'm currently working on a new EnlighterJS version including a major update of the WordPress plugin. Therefore i didn't add such feature at the moment. 

but dont't worry! i will add this feature to the upcoming major release!

best regards, Andi

**Comment by Pyknic** [comment]
Great, then I am looking forward to the next version!

**Comment by AndiDittrich** [comment]
Your feature request will be added to the next release v2.10 (additional script position option is added)

best regards, Andi
