### ISSUE TITLE
After update to 2.10, now plaintext!!

### ISSUE THREAD

**Issue by ciambellino** [AndiDittrich/WordPress.Enlighter#21]
PHP Version: 5.5.9-1ubuntu4.14
Server Software: Linux
Enlighter Plugin Version: 2.10
EnlighterJS Version: 2.10.0
Cache writeable: true
JSON Extension: installed
Wordpress 4.3.1 Diarjo Lite theme

I tried to uninstall and reinstall plugin, nothing change, all my text are in plaintext.
I enabled debug, but there aren't any relevant issue in log.

Help

**Comment by AndiDittrich** [comment]
Dear Federico,

do you have tried to click "save changes" on the plugin settings page ?
can you provide a link to your website - i think the initialization script or maybe some other javascript files are missing.

**Comment by AndiDittrich** [comment]
maybe, on the enlighters settings Page `Options >	Initialization> "Enlighter Config"` is deselected. in this case just select "inline" and click on save changes.

two options of these dropdown menu have been removed in v2.10.

**Comment by AndiDittrich** [comment]
Dear Federico,

thank's for you report. i've identified a bug which affects users when upgrading to 2.10:
the dropdown menu `Options > Initialization> "Enlighter Config"` is initialized with a wrong default value (none) which will not initialize the highlighting.
please just select "inline" and click save - this will fix the issue!

i will release a fixed version asap!
best regards, Andi

**Comment by AndiDittrich** [comment]
bug is fixed in v2.11! the update is released on GitHub and WordPress.org

**Comment by ciambellino** [comment]
Hi Andi,
thank's a lot for your fast fast fix.
Now works!

-------------------------------------
Federico Fiordoliva

Roma - Italia
Gtalk: federico.fiordoliva@gmail.com
Skype: federico.fiordoliva
-------------------------------------


2015-11-19 22:45 GMT+01:00 Andi Dittrich <notifications@github.com>:
