### ISSUE TITLE
WordPress Enlighter support bbPress and buddyPress posts?

### ISSUE THREAD

**Issue by Josua2012** [AndiDittrich/WordPress.Enlighter#22]
If the answer is no.
Are you going to support this new feature in the near future?
Thanks,
Best regards,
Jose A.

**Comment by AndiDittrich** [comment]
I didn't tried it out yet. 
Generally shortcodes may should work depending on the editor and enabled filter hooks. 
i will try to investigate it in the next view days.

best regards, Andi

**Comment by AndiDittrich** [comment]
bbPress suppot is added in v3.1-BETA6
