### ISSUE TITLE
Highlight Lines not working with Atomic theme.

### ISSUE THREAD

**Issue by CraigMcKenna** [AndiDittrich/WordPress.Enlighter#24]
Highlighting lines does not seem to work with the atomic theme.  I am not sure if this issue is related only to my site. I have tested this though by changing the theme to Enlighter.  When I change to the Enlighter theme the lines are highlighted.

If you need more information let me know.

Thank you.

**Comment by AndiDittrich** [comment]
Dear Craig,

thank's for your report. generally the line-higlighting color of the atomic theme is currently a little dark, therefore you might not see any difference to the backgound.
i will change it in the next release.

but i've found a bug on the theme customizer, which only allows the change of the highlighting color for codeblocks **with** line-numbers.

**Comment by AndiDittrich** [comment]
I've just fixed the Theme Customizer bug and updated the master (dev) branch

**Comment by CraigMcKenna** [comment]
Cool. Thanks.  In the mean time I will change it for my site.  Do you want me to submit a pull request?

**Comment by AndiDittrich** [comment]
The color is changed to `#392d3b` in the current [EnlighterJS master](https://github.com/AndiDittrich/EnlighterJS/)
