### ISSUE TITLE
Browser console warning: The specified value "t" is not a valid email address.

### ISSUE THREAD

**Issue by lots0logs** [AndiDittrich/WordPress.Enlighter#25]
The issue has already been fixed upstream (mootools/mootools-core#2705)

**Comment by AndiDittrich** [comment]
Dear Dustin,

thank you for this note. it seems to be merged in the current [v1.5.2 core release](http://mootools.net/blog/2015/09/13/mootools-1-5-2-release).
i will updated the Enlighter master asap! 

best regards, Andi

**Comment by lots0logs** [comment]
You're welcome :smile:  Cheers!
