### ISSUE TITLE
Errors after 4.4.1 upgrade

### ISSUE THREAD

**Issue by jesseandersen** [AndiDittrich/WordPress.Enlighter#26]
Running php 5.3 on an apache server for staging. Getting these errors when trying to view site after Enlighter 2.11 updgrade (from 2.9 which worked fine) with WP_DEBUG_DISPLAY set to true in wp-config (Running WP 4.4.1):

`Warning: require_once(/home/sites/mysitename/stage/releases/20160115181219/wp-content/plugins/enlighter/class/GoogleWebfontResources.php): failed to open stream: No such file or directory in /home/sites/mysitename/stage/releases/20160115181219/wp-content/plugins/enlighter/Enlighter.php on line 44 Fatal error: require_once(): Failed opening required '/home/sites/mysitename/stage/releases/20160115181219/wp-content/plugins/enlighter/class/GoogleWebfontResources.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/sites/mysitename/stage/releases/20160115181219/wp-content/plugins/enlighter/Enlighter.php on line 44`

When viewing same version of the site locally on an apache server using php 5.6 it works fine. Could there be a php version issue or server config issue?

**Comment by AndiDittrich** [comment]
Dear Jesse,

maybe the update gone wrong ?! The file was added in v2.10.

The `GoogleWebfontResources.php` file is included within the [SVN-Package](http://plugins.svn.wordpress.org/enlighter/tags/2.11/class/) (WordPress Download) as well as in the [GitHub Respository](https://github.com/AndiDittrich/WordPress.Enlighter/tree/v2.11/class).

Is the file really missing or is it maybe a cache problem (opcode cache enabled) ?

best regards, Andi
Do you've tried to reinstall the pacakage ?

**Comment by AndiDittrich** [comment]
Hi Jesse,
is the plugin now working ?
