### ISSUE TITLE
Problem with window.addEvent

### ISSUE THREAD

**Issue by grantdb** [AndiDittrich/WordPress.Enlighter#27]
I am not sure if it is a problem with another plugin on my site or is it Enlighter?  In the chrome console I get the following:

`Uncaught TypeError: window.addEvent is not a function`

Related to this code that is embedded into every page:

`window.addEvent('domready', function(){if (typeof EnlighterJS == "undefined")`

Thanks for this great plugin!

**Comment by AndiDittrich** [comment]
Dear grantdb,

the  `window.addEvent` function is provided by the MooTools Framework. if any errors like this are thrown, it's most likely related to a missing MooTools javscript file.

do you have disabled it within the Enlighter settings page ? __Enlighter -> Options -> MooTools Framework Source__ ?

normally the required script files are included by the `wp_head` template tag - does your template support it ? you can also change it to `wp_footer` within the settings page.

Maybe you can provide a link to your site (via GitHub or E-Mail)

best regards, Andi

**Comment by grantdb** [comment]
Thanks for your response. I have adjusted the settings and enabled the external script file in footer and the console error has been fixed. So it seems that having the code inlined was the issue for me.

Cheers!
