### ISSUE TITLE
EnlighterJS.custom.css cache broken for multi-server WordPress environments

### ISSUE THREAD

**Issue by aidanlane** [AndiDittrich/WordPress.Enlighter#32]
Hi, we have a load-balanced multi-server WordPress environment, hosted on AWS.

For this, the `enlighter/cache/EnlighterJS.custom.css` cache will not work properly, as one server will write it to it's cache folder and the other won't be able to access it.

This didn't seem to matter prior to version 3.0, as we don't customize the editor variables. However we can no longer access the edit functionality within existing Enlighter blocks.

Seems that `#EnlighterToolbar > .editicon` is only defined by the custom.css file.

Perhaps a workaround would be to have an extra php endpoint that can generate and return the contents of the PHP file, like WordPress does with `load-styles.php`? We could then have CloudFront cache that?

**Comment by AndiDittrich** [comment]
Dear Aidan,

normally, this issue should not happen. in case you have multiple standalone wordpress environments with a synchronized configuration (same database cluster), each instance should generate its own .css file which will be accessible by the clients.

The cached css file with the editor styles is `/enlighter/cache/TinyMCE.css` and **not** `enlighter/cache/EnlighterJS.custom.css` - the second one is only used in the frontend to define the code-styling.

therefore im wondering about, that CloudFront doesn't cache it

**Comment by aidanlane** [comment]
Hi @AndiDittrich, thanks for the speedy reply!

What triggers the generation of the CSS file?
For us, server instances are constantly spun up and terminated on AWS for horizontal scaling based on demand and for updates. So unless explicitly instructed, new (can clean) instances will not have a cached CSS file.

Oh and sorry, you're right about the CSS file for TinyMCE, I was being lazy and just copied the URL from `/wp-admin/admin.php?page=Enlighter`... I did mean `/enlighter/cache/TinyMCE.css`.

We'd be happy to come up with an elegant patch if you like :)

**Comment by AndiDittrich** [comment]
All cached CSS files are observed by the plugin - in case a file is missing or accidentally deleted, the file will be regenerated by the plugin on each request!

therefore i assume that something is going wrong in your AWS setup - does all instances share the same configuration (same database) ?

you may to take a static snapshot of these files and serving this files over CloudFront or your frontend webservers via a rewrite rule.

**Comment by aidanlane** [comment]
Apologies @AndiDittrich!

Yes, there was something wrong with our AWS CloudFront setup.
All of our other css and js files are statically stored on S3 and served up from there.
But for Enlighter, I needed to add another rule to get it to fetch via the ELB.
Also, I had to customize the TTL to 0, otherwise if a request came through and the CSS file was not yet ready, a default 404 page would be served up and stored in CloudFront with a TTL > 0 and thus would continue to be served up even after the CSS was written.

Btw, do you think that there's much overhead in constantly checking if the file exists on each request?

Thanks again for all your help!

**Comment by AndiDittrich** [comment]
the file_exists check doesn't cause a markable systems/io load. for the most use cases its the best solution to avoid caching issues. 

i will add some additional cache settings for the editing functions in the future to move this files to another location (CDN). but currently it has a very low priority

**Comment by aidanlane** [comment]
Fair enough :)
An endpoint that could be called upon by pull style CDNs would be an awesome improvement for the future.
Thanks again for all your help!
