### ISSUE TITLE
Shortcodes do not support BBPress in the newest versions

### ISSUE THREAD

**Issue by DevynCJohnson** [AndiDittrich/WordPress.Enlighter#33]
The shortcodes in the latest version of Enlighter do not work in BBPress on Wordpress 4.5.1 unless I use the "Legacy" processor. The shortcodes remain as literal text in the final post.

**Comment by AndiDittrich** [comment]
That's right. The New Shortcode processor **does not** depend on the WordPress build-in shortcode functions - therefore it is not executed by the `do_shortcode` action hook.

**Comment by AndiDittrich** [comment]
### Update ###
i will try to add a special bbpress extension to the next release - there seems to be some [filter hooks](http://etivite.com/api-hooks/bbpress/trigger/apply_filters/bbp_get_topic_content/) available to modify the post-content:

- `bbp_get_reply_content`
- `bbp_get_topic_content`

i'm not very familar with bbpress - is it required to apply the shortcode filter to other "content sections" ?

**Comment by DevynCJohnson** [comment]
Thanks! Only bbp_get_reply_content and bbp_get_topic_content are needed.

**Comment by AndiDittrich** [comment]
Hi Devyn!

i've implemented bbPress Shortcode support. it is available in the latest dev version (3.1-BETA6) https://github.com/AndiDittrich/WordPress.Enlighter/archive/master.zip

I would appreciate your feedback

**Comment by AndiDittrich** [comment]
v3.1 is out including experimental bbPress shortcode support - you may have to care of your theme - some bbPress styles seems to break Enlighter's appearance
