### ISSUE TITLE
timyMCE backend not save data

### ISSUE THREAD

**Issue by ciambellino** [AndiDittrich/WordPress.Enlighter#36]
Hi, when i create an enlighter box i can view my text enlighting, when i add some change like "Point out Lines", or "Linennumber offset" or "Codegroup Identifier" or "Codegroup Title" the data disappear after i close dialog interface.

After update to 4.5.2 all worked fine.

Step to reproduce:
1- wordpress fresh install 4.5.2
2- install enlighter 3
3- create my first post
4- write text to enlighter box
5- click on enlighter text and open a box for customize it
6- write some text/number on every textbox like above.
7- click OK button
8- click on enlighter text and open a box for customize it
9- textfield are blank

My System info.

PHP Version: 5.5.9-1ubuntu4.16
Server Software: Linux
Enlighter Plugin Version: 3.0
EnlighterJS Version: 2.10.0
Cache writeable: true
JSON Extension: installed
Shortcode Processor: Enlighter low-level

Thanks!!

**Comment by AndiDittrich** [comment]
Dear Federico,
which user-role are you using ? Author or contributor ? Maybe it is related to the  following issue mentioned on WordPress.org Forums https://wordpress.org/support/topic/snippet-option-not-saving-for-authors

do you've tried the latest beta ?

**Comment by ciambellino** [comment]
I'm administrator.
I didn't try latest beta.
I will make a test asap.

Federico Fiordoliva
site: www.oneos.it
skype: federico.fiordoliva
Il 23 mag 2016 12:55, "Andi Dittrich" <notifications@github.com> ha scritto:

**Comment by ciambellino** [comment]
ok!
with 3.1-BETA6 works!
How long for the version 3.1 release?

thanks!

-------------------------------------
Federico Fiordoliva

Roma - Italia
Gtalk: federico.fiordoliva@gmail.com
Skype: federico.fiordoliva
Web:   https://www.oneos.it

-------------------------------------


2016-05-23 13:53 GMT+02:00 Federico Fiordoliva <
federico.fiordoliva@gmail.com>:

**Comment by ciambellino** [comment]
ops
3.1 stable

-------------------------------------
Federico Fiordoliva

Roma - Italia
Gtalk: federico.fiordoliva@gmail.com
Skype: federico.fiordoliva
Web:   https://www.oneos.it

-------------------------------------


2016-05-23 14:15 GMT+02:00 Federico Fiordoliva <
federico.fiordoliva@gmail.com>:

**Comment by AndiDittrich** [comment]
approx at the end of the week or this weekend. i am currently finalizing the release.

btw. are you using any other editing plugins ? generally Enlighter works with administrator privileges - the new version does only fix an issue related to contributors/authors, which are not allowed to post unrestricted html. it seems that the wordpress KSES filter is enabled for your account.

**Comment by ciambellino** [comment]
Is KSES enabled in default installation?
I only used wordpress as default when i made a test and enlighter was the
only plugin installed.

-------------------------------------
Federico Fiordoliva

Roma - Italia
Gtalk: federico.fiordoliva@gmail.com
Skype: federico.fiordoliva
Web:   https://www.oneos.it

-------------------------------------


2016-05-24 8:59 GMT+02:00 Andi Dittrich <notifications@github.com>:

**Comment by AndiDittrich** [comment]
v3.1 is out!
