### ISSUE TITLE
Code indentation gone

### ISSUE THREAD

**Issue by Suleiman56060** [AndiDittrich/WordPress.Enlighter#38]
My code snippets have suddenly lost their indentation. This is highly frustrating as I use your plugin throughout my blog and this is an issue site wide (running Wordpress 4.5.3).
![screen shot 2016-07-01 at 6 06 04 pm](https://cloud.githubusercontent.com/assets/19791360/16521740/87494f3e-3fb6-11e6-8913-62d8d63170ee.png)
The only recent changes I remember is adding the following plugin:
WP Fastest Cache

I also feel auto-indentation of code could be an added feature to the plugin. This could help avoid similar such issues in the future.

Hope to get this resolved at the earliest.

**Comment by AndiDittrich** [comment]
HI Suleiman,

did you use the "Code Insert Dialog" ? Can you post a public url to your blog ?

**Comment by Suleiman56060** [comment]
I always use the "Code Insert Dialog".
Here's the [URL](http://blog.grafixartist.com/)
The thing is, code on posts that were previously published have lost indenting as well.

UPDATE: The indentation is not permanently lost. It's a hit or miss each time while loading the blog.

**Comment by AndiDittrich** [comment]
Ok!
The issue seems to be caused by **another plugin** you are using on your website.

**ALL** identations within your page source at the start of a line are missing - i believe it is a caching/optimization plugin enabled on your site.
Try to disable these plugins and in case you are using a frontend cache - flush it to apply the changes

**Comment by AndiDittrich** [comment]
From the [WP Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/) documentation:

> Performance Optimization
> ...
> Minify Html - You can decrease the size of page

this may cause your issue
