### ISSUE TITLE
upgrading plugin breaks my things

### ISSUE THREAD

**Issue by cavaunpeu** [AndiDittrich/WordPress.Enlighter#41]
andi,

plugin was previously working perfectly. now, my syntax-highlighted code looks as follows:

<img width="735" alt="screen shot 2016-07-26 at 6 40 17 pm" src="https://cloud.githubusercontent.com/assets/7306239/17146892/817900dc-5360-11e6-881b-6f669ee2dd91.png">

what's my play?

**Comment by AndiDittrich** [comment]
Dear cavaunpeu,

can you please post a url from your blog ?
Are any other syntax highlighting plugins active ? if so, please disable them!

did you paste your code snippet directly into the VisualEditor or did your use the "Code Insert Dialog" ?

best regards, Andi

**Comment by cavaunpeu** [comment]
WP Markdown plugin was creating havoc. Disabled, and now working. Closed.
