### ISSUE TITLE
Please add custom hook to setupFrontend method

### ISSUE THREAD

**Issue by khosroblog** [AndiDittrich/WordPress.Enlighter#44]
Hi, and thank you for this helpful plugin. :)
I use Enlighter plugin for comments and I need for access wp_editor buttons to all users include subscribers. so please add a custom hook to setupFrontend method of Enlighter Class.

```php
 public function setupFrontend(){
        // load frontend css+js resources
        $this->_resourceLoader->frontendEnlighter();

        // check frontend user privileges
        $canEdit = is_user_logged_in() && (current_user_can('edit_posts') || current_user_can('edit_pages'));

      ########## I need to this hook ########################
      $canEdit = apply_filters("enlighter_can_edit", $canEdit );
      #######################################################

        if ( $canEdit ){
            $this->_resourceLoader->frontendEditor();
        }
    }
```

**Comment by AndiDittrich** [comment]
Dear khosroblog ,

no problem, i will add this filter hook asap (but renaming it) ;)

best regards, Andi

**Comment by khosroblog** [comment]
Thank you andi :+1:

**Comment by AndiDittrich** [comment]
## FILTER::enlighter_frontend_editing ##

**Description:** Forced enabling/disabling of the frontend editing functions. The default value is created by the condition `USER_LOGGED_IN AND (CAN_EDIT_POSTS OR CAN_EDIT_PAGES)`. Useful to bind editing capabilities to special users/groups 

#### Example 1 - Limit editing functions to admin users ####

```php
function mm_ejs_frontend_editing($allowed){
      return ($allowed && current_user_can('manage_options'));
}

// add filter
add_filter('enlighter_frontend_editing', 'mm_ejs_frontend_editing');
```

**Comment by khosroblog** [comment]
Perfect ;)
