### ISSUE TITLE
Can I use two language in one code highlighting?

### ISSUE THREAD

**Issue by rizaldimaulidia** [AndiDittrich/WordPress.Enlighter#51]
Hi!
My question is simple. Can I use two language in one code highlighting? I want to use php code and html code in one code highlighting.

Thank you.

**Comment by AndiDittrich** [comment]
Hi,
short answer: **currently not possible**

hybrid code support is projected for EnlighterJS v3.1...3.3 - i'm currently working on the v3.0 release - it will take some time until the feature will become available

best regards, Andi

**Comment by rizaldimaulidia** [comment]
Ohh..
I will waiting for that feature. Thank you very much.
