### ISSUE TITLE
PHP 5.3 fault after version 4.6 

### ISSUE THREAD

**Issue by crislv90** [AndiDittrich/WordPress.Enlighter#52]
Hello,
At some point, after I upgraded WordPress automatically, I think to 4.6, the enlighter plugin stopped working.  I now get the python $this reference error below:

Fatal error: Using $this when not in object context in /home/username/public_html/wp_name/wp-content/plugins/enlighter/class/ShortcodeFilter.php on line 85

Any idea what I need to do ?
Thanks

**Comment by AndiDittrich** [comment]
Sounds like a lambda function issue.
Do you use PHP < 5.4 ?

best regards, Andi

**Comment by crislv90** [comment]
Oh, sorry, I meant php not python .. ;-)
Yes, here is my php version:
PHP 5.3.10-1ubuntu3.25 with Suhosin-Patch (cli) (built: Oct  3 2016 17:02:21)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Suhosin v0.9.33, Copyright (c) 2007-2012, by SektionEins GmbH

**Comment by AndiDittrich** [comment]
Thanks! i will fix it asap.

**Comment by AndiDittrich** [comment]
Please try v3.3-BETA3 (GitHub Master Branch)

**Comment by crislv90** [comment]
Almost there ...

You need to change this:

 private $_codeFragments = array();

to this:

 public $_codeFragments = array();

Otherwise, I get this error:

Fatal error: Cannot access private property Enlighter\ShortcodeFilter::$_codeFragments in /home/username/public_html/wp_name/wp-content/plugins/enlighter/class/ShortcodeFilter.php on line 88

Once I made the array public, it works great .

Thanks

Cris

**Comment by AndiDittrich** [comment]
Thanks! I didn't test it yet because i have no php 5.3 installation anymore.

btw. i will drop the PHP 5.3 support in the future. Currently most users use a modern version https://wordpress.org/about/stats/

**Comment by crislv90** [comment]
My ISP has php 5.3 .. I will see if they would run the upgrade .. 
if not, at least I know your trick of passing "$this" to any lambda as a generic $T .. if I ever need to again ..
Thanks

**Comment by AndiDittrich** [comment]
v3.3 is out
