### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS message when trying to access admin

### ISSUE THREAD

**Issue by sassyjg** [AndiDittrich/WordPress.Enlighter#53]
When trying to access WP admin, I am now receiving this error message:

> The ... page isn’t working
> 
> .... redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

And URL changes to:

> /wp-admin/admin.php?page=Enlighter-About

This occured after deactivating and reactiving several site plugins, including Enlighter. 

Please advise!

**Comment by AndiDittrich** [comment]
Thanks for your report.
I will check this issue. Generally the "About Page" should only be shown on plugin activation/update - in this case a single redirect is triggered. Sound like a side effect with another plugin. do you've tried to use Enlighter alone on your testing site ?

best regards, Andi

**Comment by AndiDittrich** [comment]
Dear sasssyjg,

curently, i cannot reproduce your issue.

do you have any **caching/optimize plugins** installed ? in case a `delete_option` command within the Enlighter Startup code fails, such infinite redirect may happen on Enlighter plugin activation.

**Comment by AndiDittrich** [comment]
Please try the [latest beta release](https://github.com/AndiDittrich/WordPress.Enlighter/archive/master.zip) (3.3-BETA5) - i've added an additional check to ensure that the redirect flag has been removed. 

I believe your issue is caused by a broken 3rd party caching plugin

**Comment by sassyjg** [comment]
Perfect. In order to get the admin back up, I had commented out the redirect on the previous version of the plugin. I agree the issue is the result of a conflicting plugin, and am doing tests now to determine which one.

Thanks so much for your help.
