### ISSUE TITLE
Fatal error after updating plugin

### ISSUE THREAD

**Issue by AndreKrebs** [AndiDittrich/WordPress.Enlighter#54]
I updated the plugin, my Wordpress stopped working and displays the following error on the screen:

Fatal error: Using $this when not in object context in /home/krebs284/public_html/wp-content/plugins/enlighter/class/ShortcodeFilter.php on line 85

I had to disable it to make the site work.

**Comment by AndiDittrich** [comment]
Dublicate #52 
The issue has already been fixed in the master branch. the release will follow within the next few days

best, regards, Andi

**Comment by AndiDittrich** [comment]
v3.3 is out including the fix
