### ISSUE TITLE
Faster way to insert inline code?

### ISSUE THREAD

**Issue by searene** [AndiDittrich/WordPress.Enlighter#63]
In the visual editor, I found two following ways to insert inline code(e.g. `code`) with Enlighter.

* Click on `Enlighter Code Insert` on the toolbar, choose `Inline-Code` as the `Mode`, input the source code in `Sourcecode`, click on `OK` to insert it.

![screenshot from 2017-04-08 14-42-06](https://cloud.githubusercontent.com/assets/3351317/24826472/98721a4e-1c69-11e7-8aea-88e0af2a7e95.png)

There are too many steps in here so I wouldn't consider it a good idea to do so.

* Another way: Input \`code\` in the editor, then I saw \`code\` was processed automatically by WordPress, and the rendering was not good

![screenshot from 2017-04-08 14-44-34](https://cloud.githubusercontent.com/assets/3351317/24826501/03e5297e-1c6a-11e7-8824-b62734a96fc0.png)

then I pressed `Backspace` to cancel the rendering, so \`code\` could be processed by `Enlighter`.

![screenshot from 2017-04-08 14-44-47](https://cloud.githubusercontent.com/assets/3351317/24826502/04c46670-1c6a-11e7-8101-5a1ced16609d.png)

This is better than the first way, but I have to press `Backspace` each time to let WordPress cancel its own `<code>` rendering.

I don't know there is any other way to insert inline code, if not, is it possible to stop WordPress from trying rendering \`\` itself, so we don't need to press `Backspace` each time? Or maybe we can find another way to insert inline code quickly, like set up another shortcut? Or maybe override the default rendering of the `<code>` tag? Because a lot of people tend to use inline code a lot. It would be great if we can do this as fast as possible.

I'm using WordPress 4.7.3.

**Comment by searene** [comment]
Hi Andi,

Thank you for your reply. I saw this option too, and it also took a long time to do that because there was no shortcut, so I didn't mention it. I think backtick + code + backtick + `backspace` is still the fastest way to insert inline code so far, it works great, only that I have to press an additional `backspace` each time.

Once WordPress detects \`inline\`, it will try to wrap `inline` with the `<code>` tag, make it `<code>inline<code>`, then render it. I think the best way to insert inline code is to try to let Enlighter take care of the `<code>` tag, render it in our own way. So we can just use \`\` to insert inline code without using mouse to click on lots of buttons/icons. Although I'm not sure if it's possible.

And I think for inline code, the language identifier pattern is not that necessary, just rendering it in a generic way would be great in most cases.

Regards,
Searene

**Comment by AndiDittrich** [comment]
Dear searene,

thats already possible. just goto `Enlighter Settings > Options > Advanced Options` and use `code` as **Inline CSS Selector**. This forces EnlighterJS to select all `<code>` elements and highlight it.

additionally, set **Generic Highlighting** as default language

best regards, Andi

**Comment by searene** [comment]
Hi Andi,

I tried, and it worked! Thank you for creating such an amazing plugin!

Wouldn't it be great if we set it as the default behavior? I doubt if anyone will need WordPress's rendering version if they have Enlighter to render `<code>` in a better way. 

Regards,
Searene

**Comment by AndiDittrich** [comment]
That would be great ...but it may causes side-effects with themes or widgets if there is no selector-scope (they may use the `code` tags for other purpose).
To avoid such behaviour/bad user experienced i've added the `EnlighterJSRAW` class to all elements which are created/managed by the plugin.

**Comment by searene** [comment]
Hi Andi,

It made sense, thanks for making and maintaining this amazing plugin for such a long time.

Regards,
Searene
