### ISSUE TITLE
How to change the top margin (or padding?) of inline code style?

### ISSUE THREAD

**Issue by Kongsea** [AndiDittrich/WordPress.Enlighter#64]
I have used the Enlighter to highlight my code in WordPress and I have some problems now.

1. The top margin/padding of inline code style is too small and it seems the code was cut from the top.
2. The code block style works very well, but the bottom of the code block always has a big empty area.

And you can click the link to visit my blog and see the problems: <a href='http://www.yueye.org/2017/cross-with-ubuntu-terminal-using-shadowsocks.html'>an example</a>
So could anybody give some advice to fix the problems? Thank you very much.

**Comment by AndiDittrich** [comment]
Dear Kongsea,

some of the EnlighterJS style interfer with your theme styles. you can fix this by adding the following CSS rule:

```css
span.EnlighterJS{
  display: inline-block;
}
```

**Example**
![enlighter_fix](https://cloud.githubusercontent.com/assets/1474107/25301960/38416b46-2733-11e7-8462-6eb7f078a672.png)

**Comment by Kongsea** [comment]
Thank you.
Now it looks good.
