### ISSUE TITLE
code and pre tags inside Enlighter block

### ISSUE THREAD

**Issue by typistX** [AndiDittrich/WordPress.Enlighter#65]
So I'm wrapping Python code with [python][/python], but it seems that something is causing \<pre>\<code> tag pairs to appear at the first occurrence of indentation. 

Using a self hosted install, writing in Markdown (Jetpack)

**Comment by AndiDittrich** [comment]
The Markdown plugin causes the issue...you have to disable the markdown code highlighting (4 space indentation is interpreted as codeblock)

**Comment by typistX** [comment]
Hi Andi and thanks for replying. I have found that if I surround Enlighter's shortcode with three backticks, everything is fine. Is that a bad idea though? 

How would I go about turning off md code highlighting?

**Comment by AndiDittrich** [comment]
I'm not sure what happened in this case...but i recommend you to use Enlighters build-in fenced codeblock highlighting (markdown style) instead of shortcodes. This should prevent such issues.

To enable it, goto **Enlighter -> Editing -> Markdown** and select **Enable the_content**

**Comment by typistX** [comment]
Hmmm, so `Enable the_content` is ticked, but when I write something like:

```
```
def hello():
    print("Hi!")
```
```

It just prints my normal CSS and not Enlighter's.  Even if I put `python` after the three backticks.

**Comment by AndiDittrich** [comment]
i will try to reproduce your issue... that's not the intended/normal behaviour.... i believe it's an issue with your markdown plugin... did you tried to disable it ?

**Comment by AndiDittrich** [comment]
i can confirm that this is an jetpack related issue in case markdown is active...i will try to investigate it...

**Comment by typistX** [comment]
> i can confirm that this is an jetpack related issue in case markdown is active...i will try to investigate it...

Thank you. If it helps, the Markdown plugin of Jetpack is based on a plugin that was once open-source, it's/was called Markdown on Save/Markdown on Save improved. To be honest I still have it on, but I don't think it is the source, but rather JP as you said. (The problem is that WP.com cannibalized the independent developers sphere and I honestly couldn't find a single backward-compatible plugin for writing in Markdown.)

**Comment by typistX** [comment]
I can confirm that the same behavior occurs with at least another plugin: [WP-Markdown](https://wordpress.org/plugins/wp-markdown/stats/). I turned off Jetpack before trying this so it's not just this specific plugin.

**Comment by AndiDittrich** [comment]
Dear typistX,

the problem of both plugins is the following "feature" of them

> converts the Markdown into HTML prior to saving the post.

this means that they convert the markdown content to html on finishing the **page edit**.
on the other hand, Enlighter highlights or better say processes the code on **page rendering** .. therefore the markdown engines are invoked prior the Enlighter plugin - it is an incompatibility by design

there is no real workaround in my opinion. maybe you find another markdown plugin which does not modify the content.

i plan to release a custom markdown plugin based on [LightUp](https://github.com/AndiDittrich/LightUp) soon :)
