### ISSUE TITLE
Incorrect syntax highlighting before page refresh

### ISSUE THREAD

**Issue by Thibstars** [AndiDittrich/WordPress.Enlighter#66]
I'm using Enlighter on my blog, and I've had multiple notifications of incorrect source code highlighting. However, when I checked, the settings where correct. I have set the default highlighting language to Java.

In fact, I've seen the issue myself, the code wasn't readable at all, looked like a bunch of HTML tags. When refreshing the page, everything was just fine.

I know this issue is pretty vague, but at this time I can't provide screenshots or fixed reproduction steps. I will update the issue if that changes.

**[EDIT]** I managed to catch the behavior in a screenshot:
![capture](https://cloud.githubusercontent.com/assets/6588019/25852927/499638b8-34cb-11e7-801d-15de87349802.PNG)
While this was expected to be displayed:
![capture](https://cloud.githubusercontent.com/assets/6588019/25852978/7669a2b2-34cb-11e7-8a38-b528d1b12d32.PNG)

This happened after updating the post and displaying it in preview mode.

**[EDIT]** When this happens in IE, a refresh doesn't seem to do the trick.

**Comment by AndiDittrich** [comment]
Dear Thibstars,

of course..that sounds very myterious...

one "standard" issue of plain-html code can be an incorrect delivered page - this can be caused by some PHP exeptions during page rendering (abort page loading). did you've looked into your servers error-log ?

br Andi

**Comment by Thibstars** [comment]
@AndiDittrich Thanks for your prompt reply!

Hmm, what are common reasons of abort page loading? I haven't yet looked into the error-log, is there anything I can search for in particular?

**Comment by AndiDittrich** [comment]
it could be everything...mostly some defect WordPress plugins/bad PHP settings. in such case a **fatal error** will appear within the logs
