### ISSUE TITLE
Disable unordered list too when line number is disable.

### ISSUE THREAD

**Issue by jigs031** [AndiDittrich/WordPress.Enlighter#68]
When "line number" is disabled it treats each line as unorder list items and shows the dot in front of every line. It should not display any prefix when line number is disable or should be configurable.
This is very helpful in case user wants to embed code results, boxed paragraph or important notes.

**Comment by AndiDittrich** [comment]
Dear jigs031,

thanks for your report.

the behaviour you've described is not intended and not observed before. EnlighterJS default css rules will not display any css list-style on unorderer `<ul>` lists. It seems that your WordPress theme css is overriding the EnlighterJS CSS Rules - please check this within your Chrome/Firefox DOM Inspector :)

br, Andi
