### ISSUE TITLE
Grab Pre-Selected Text Automatically

### ISSUE THREAD

**Issue by aeromusek** [AndiDittrich/WordPress.Enlighter#77]
I would love to highlight a section of text in the WordPress editor, click the Enlighter Code Insert button, and have that text entered directly into the snippet editor.

Extra credit if it defaults to 'inline' when there is no line break in the selection!

Mockup of flow: 
![enlighter example](https://user-images.githubusercontent.com/7685059/29340736-c6b2a3e0-81dd-11e7-8327-fc517f08062b.gif)

**Comment by AndiDittrich** [comment]
Hi Alex,

thanks for your proposal (and great mockup ;))

technically it is possible to implement it. but whats about the **Editor Formats** (EditorToolbar -> Formats -> Enlighter Block/Inline -> Language) - they are exactly designed for this purpose.

best regards, Andi

**Comment by aeromusek** [comment]
Dang...yes, that is *exactly* what I wanted. It did seem weird that this would be missing from such an otherwise polished plugin, and I promise I did look everywhere I could think of to find it!

Okay, cancel this request 😌

**Comment by AndiDittrich** [comment]
in part it's my fault because a good documentation/tutorial is currently missing :( i'm sorry about this

have fun with Enlighter!
