### ISSUE TITLE
XML not being highlighted

### ISSUE THREAD

**Issue by Suleiman19** [AndiDittrich/WordPress.Enlighter#8]
Hi, I post some android XML code snippets over at my blog here http://blog.grafixartist.com/
The thing is the syntax doesn't highlight properly, or doesn't highlight at all! Here's an example post where you can see how the XML is: http://blog.grafixartist.com/diy-floating-action-button-part-2/

It works fine for Java and other languages I've tried. But this one refuses to color the syntax correctly.
![untitled](https://cloud.githubusercontent.com/assets/12139017/7593666/6db2d068-f8f9-11e4-8680-e8b50c2a0646.png)

**Comment by AndiDittrich** [comment]
Dear Suleiman19,
thank's for your report.
i can confirm that this is a bug within the EnlighterJS XML Tokenizer (multiline xml tags) - i've fixed it into the development version. 
the release of EnlighterJS 2.5 will follow next week; the Enlighter WordPress plugin will be updated in approx 2 weeks

best regards, Andi

**Comment by Suleiman19** [comment]
Wow thanks for the quick reply. This great.
Lovely plug in BTW :-)

**Comment by AndiDittrich** [comment]
Fixed in v2.6 - release is available on GitHub and [WordPress.org](https://wordpress.org/plugins/enlighter/)

**Comment by Suleiman19** [comment]
Thanks I can confirm its working now :)

On 17 May 2015 at 18:51, Andi Dittrich <notifications@github.com> wrote:

> Fixed in v2.6 - release is available on GitHub and WordPress.org
> <https://wordpress.org/plugins/enlighter/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndiDittrich/WordPress.Enlighter/issues/8#issuecomment-102804042>
> .
>



-- 
*In need of graphics, a website or maybe an app?*
I could make one for you. It's what I love doing.
Head over to my website <http://grafixartist.com/> to get in touch.
