### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by bobmosh** [AndiDittrich/WordPress.Enlighter#81]
Hey Andi,

first of, incredible Plugin. I am loving it so far.
Better than anything else I've found so far!

I searched through the history of issues and in issue number #23 you pointed out, that Swift will be added in the new release. Will Swift be added to the list of languages?

If not, is there a way to allow for custom languages to make it possible myself?

Hope to hear from you!

Cheers,
Ferdinand

**Comment by AndiDittrich** [comment]
Hi Bob,

**swift** support has been added to EnlighterJSv3 but it is not released yet. It will not be implemented in the current v2. if you like you can create your own [EnlighterJS Language](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Language/Template.mylang.js).

**EnlighterJS3 Swift Example**

![enlighterjs3_swift](https://user-images.githubusercontent.com/1474107/30100828-6a893ce6-92ea-11e7-93c7-a6cf21c38a8e.png)

best regards, Andi
