### ISSUE TITLE
Hello Great Plugin but need some updates look inside bro

### ISSUE THREAD

**Issue by theghostbh** [AndiDittrich/WordPress.Enlighter#83]
hello 
Need to arrange codes so that the spaces
And also add to vb.net

**Comment by theghostbh** [comment]
i talk about Enlighter - Customizable Syntax Highlighter plugin

**Comment by AndiDittrich** [comment]
i know but I didn't catch the sentence:

> Need to arrange codes so that the spaces

VisualBasic Support has already been requested in is [implemented in EnlighterJS4 ](https://github.com/AndiDittrich/EnlighterJS/issues/23#issuecomment-231594274)(will be available within the next major Enlighter WordPress Release v3)

best regards, Andi
