### ISSUE TITLE
WhiteScreenOfDeath

### ISSUE THREAD

**Issue by reatlat** [AndiDittrich/WordPress.Enlighter#86]
PHP 7.1.9
WP 4.8.2
enlighter 3.5

after activation plugin [WP No External Links](https://wordpress.org/plugins/wp-noexternallinks/)
Front-end goes down, debug mode shows nothing!

**Comment by AndiDittrich** [comment]
hi alex,

did you checked the servers php error.log ? normally it throws some errors in this case

**Comment by reatlat** [comment]
@AndiDittrich I have some errors, but it's my errors which were before, for test it and be sure this error comes after activation this plugin and trying to render front-end.... but nothing! error.log is empty :( Have no idea....
how to grab issue if everything empty.... 
I will try to make a local copy for test and will try to grab a log...

**Comment by AndiDittrich** [comment]
I've tried to reproduce your issue (Enlighter+NoExternalLinks) but everything worked as excpeted

```
PHP Version: 5.6.30-0+deb8u1
Server Software: Linux
Enlighter Plugin Version: 3.5
EnlighterJS Version: 2.11.1
WordPress: 4.8.2
```

**Comment by reatlat** [comment]
@AndiDittrich I use PHP version 7.1.9 ... 
not sure why it's not working... maybe problem in my theme...
I will try to find the issue...

**Comment by reatlat** [comment]
@AndiDittrich problem in my child theme :(
sorry for taking your time...
#close
