### ISSUE TITLE
WordPress 4.9 compatibility?

### ISSUE THREAD

**Issue by oldrup** [AndiDittrich/WordPress.Enlighter#89]
Not really an issue, more a question. Is Enlighter still being maintained and maybe even tested with WordPress 4.9?

On wordpress.org, it is listed as compatible up to WordPress 4.8.3
https://wordpress.org/plugins/enlighter/

Kind regards,
Bjarne

**Comment by AndiDittrich** [comment]
Hi Bjarne,

thanks for your advice. i didn't update the SNV-Tag only the trunk ... 

best regards, Andi
