### ISSUE TITLE
Can't display ">" and "<" characters

### ISSUE THREAD

**Issue by marcoschwartz** [AndiDittrich/WordPress.Enlighter#9]
Hello,

I have a problem with Enlighter on all my Wordpress sites: the ">" and "<" characters are not displayed correctly and are replaced by &gt. An example:

https://openhardwarerobots.com/digital-compass-arduino-robot-nagivation/

Can you help? Thanks

**Comment by AndiDittrich** [comment]
Dear marco,

could you provide a working example (e.g. private demo page) ? are you using shortcodes or the VIsualEditor mode ?

Enlighter will replace "< >" characters with the corresponding escape sequences to avoid html syntax errors but the will be re-replaced during the javascript rendering process. normally such error should not happen. i've just take a look onto the unit tests an everything looks like expected.

best regards, Andi

**Comment by marcoschwartz** [comment]
Hello Andi,

Thanks for the fast response! You didn't see it in the page I sent you? It's basically on all my pages. For example also on: https://www.openhomeautomation.net/control-a-lamp-remotely-using-the-esp8266-wifi-chip/

I am using the 'Enlighter Code Insert' button in Wordpress:

![screen shot 2015-05-29 at 10 25 29](https://cloud.githubusercontent.com/assets/1475795/7879061/2907ce9a-05ed-11e5-955e-5e9aa601cded.png)

Inside a post when editing it looks fine:

![screen shot 2015-05-29 at 10 25 37](https://cloud.githubusercontent.com/assets/1475795/7879064/2ee5daa0-05ed-11e5-96f9-b168de79a2e4.png)

Following your comment I tried to switch the code type to C++, but it didn't help.

Cheers,
Marco

**Comment by AndiDittrich** [comment]
but you're not using Enlighter for highlighting. the crayon syntax highlighter plugin take over the Enlighter elements!

**Comment by marcoschwartz** [comment]
Oh got it ... so I should uninstall Crayon ?

**Comment by AndiDittrich** [comment]
You should disable it to use Enlighter.. ;) But be aware of the design changes because Enlighter uses it's own Themes http://enlighterjs.andidittrich.de/Themes.html which can be customized

**Comment by marcoschwartz** [comment]
Ok thanks, will do :)
