### ISSUE TITLE
how can i increase font size on the Wordpress plugin

### ISSUE THREAD

**Issue by Edge-Developer** [AndiDittrich/WordPress.Enlighter#90]
I absolutely love the plugin, how can i increase its font size in  wordpress?

**Comment by AndiDittrich** [comment]
Hi Edge-Developer,

you can use the Theme Customizer to change the font-size of the highlighted code or use a custom theme.

br, Andi

**Comment by Edge-Developer** [comment]
Thank you @AndiDittrich for the quick response but under Theme Customizer for enlighter i couldnot find font-size

**Comment by AndiDittrich** [comment]
![enlighter fontsize](https://user-images.githubusercontent.com/1474107/33239360-da106210-d2a0-11e7-9226-e0338830d609.jpg)

**Comment by Edge-Developer** [comment]
![capture](https://user-images.githubusercontent.com/22748496/33239373-423e27f0-d2a1-11e7-94bc-c22943ff24e6.PNG)

**Comment by AndiDittrich** [comment]
you have to select "WPCustom" as theme to enable the Customizer

**Comment by Edge-Developer** [comment]
i guess we don't have the same menu

**Comment by Edge-Developer** [comment]
does it only work with WPCustom?

**Comment by Edge-Developer** [comment]
Oh! I get it Now. I thought you were referring to the Wordpress theme itself

**Comment by AndiDittrich** [comment]
;)

**Comment by jaradc** [comment]
Had same issue ad Edge-Developer today. This wasn't immediately obvious to me either.

**Comment by fibeesoft** [comment]
Hey, Im trying to increase the font size of the code but doesnt work for me...
![image](https://user-images.githubusercontent.com/36067069/79644602-4e853e80-81aa-11ea-8681-70b94515e574.png)
Is it a bug or should I do it some other way? I tried with pixels and em but both had no effect.
Can you help please?

**Comment by AndiDittrich** [comment]
@fibeesoft 

the code font size cannot be changed with the "global" option currently - i will add it to the next release

**Comment by fibeesoft** [comment]
Thank you, that would be great as the code's font size is pretty small and hard to read at the moment :)

**Comment by AndiDittrich** [comment]
just add some custom css to override it as workaround

**Comment by fibeesoft** [comment]
Can it be done in a global scope if yes then where? Because I can see only a custom css with each instance of the code used in the article but I add quite a lot of short snippets so that would be inefficient to change css for each of them?

**Comment by AndiDittrich** [comment]
just add it to your wordpress theme

**Comment by fibeesoft** [comment]
.enlighter-t-wpcustom{
	font-size: 2.2em;
	color: #212529;
	background-color: #f8f9fa;
	padding: 25px 25px 25px 25px;
	font-family: "Source Code Pro","Liberation Mono","Courier New",Courier,monospace;
	font-style: normal;
	font-weight: normal;
	line-height: 2.6em;
}
Would that be this part?

**Comment by AndiDittrich** [comment]
no... use the following selector:

```css
.enlighter-t-wpcustom .enlighter span{
font-size: 20px;
}
```

**Comment by fibeesoft** [comment]
ok, thank you

**Comment by fibeesoft** [comment]
Im afraid it doesnt work with customizr, I tried with style.css and built in css and both had no result. Anyway.. I'll wait for the next release :)

**Comment by AndiDittrich** [comment]
can you post a link to you website ?

**Comment by fibeesoft** [comment]
http://pikademia.pl/2020/04/18/petla-for/

**Comment by AndiDittrich** [comment]
you've selected bootstrap4 as theme and not the customizer...in this case you have to change the selector

```css
.enlighter-t-bootstrap4 .enlighter span{
font-size: 20px;
}
```

**Comment by fibeesoft** [comment]
Works like the charm. Thank you so much :)

**Comment by richiwalt** [comment]
Is there a way to add a bit of CSS to change the background color to match my theme ?

**Comment by AndiDittrich** [comment]
@richiwalt 

just use the theme customizer. btw please open a new issue/support request next time..
