### ISSUE TITLE
/wp-admin/admin.php?page=Enlighter-About shown on ANY plugin activation

### ISSUE THREAD

**Issue by oldrup** [AndiDittrich/WordPress.Enlighter#91]
Thanks for a great plugin, it's appreciated 👍 

One small quirk - the page wp-admin/admin.php?page=Enlighter-About is in my installation shown at ANY plugin activation, not only when Enlighter is activation, and there does not seem to be any dismiss feature.

Missing something or just my setup?

Bjarne

**Comment by AndiDittrich** [comment]
Hi Bjarne,

thanks for your repost. it may be caused your setup...some other users reported similar issues in the past but the enlighter plugin has a protection which displays the notification only 1time. in the past i couldn't reproduce the issue in any of my setups :( dou you use any caching plugins like memcache or redis ?

**redirect sequence**
1. a "new" version must be available (database version != file version) https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/class/Enlighter.php#L358
2. an option flag will be set in the database https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/class/Enlighter.php#L325
3. which triggers the "redirect" action on the next plugin activation https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/class/Enlighter.php#L100

im not sure what exactly happens. maybe the "upgrade flag" didn't get removed or the `wp_redirect` http redirect will be cached by your browser

best regards, Andi

**Comment by oldrup** [comment]
Thanks for the support. I immediately tried with my caching plugin disabled, but that didn't help. Enlighter keeps showing its about page after any plugin activation.

I also browsed through and saved the settings a couple of times.

System info is 
PHP Version: 7.1.12
Server Software: Linux
Enlighter Plugin Version: 3.5
EnlighterJS Version: 2.11.1
Cache writeable: true
JSON Extension: installed
Shortcode Processor: Enlighter low-level

Its by all means not a critical issue, just odd. 

Site using Enlighter (still under active development): http://oldrup.net/extra/category/css-snippets/

Kind regards
Bjarne

**Comment by AndiDittrich** [comment]
Hi Bjarne,

thanks for your response. currently i believe it's an issue with the browser cache (cached redirect). 
could you please try to activate a plugin with enabled **Developer Console** and **Preserve Log** option ?

within the log i expect a cached 302 redirect request to `admin.php?page=Enlighter-About` 

![enlighter_webdev_debug](https://user-images.githubusercontent.com/1474107/34488753-f9657ffa-efd9-11e7-9ef9-565778516825.png)

after this you can try to enable the **Disable Cache** flag - in case it is a caching issue the error should not happend as long as the flag is set.

best regards, Andi

**Comment by oldrup** [comment]
Hi Andi

Well that's funny... After doing what you suggested, the problem is gone. Once I enabled the "Disable Cache" option, it was working just fine. Even when I closed developer console ...

Thank you for your time and support :) 👍 

Bjarne

**Comment by AndiDittrich** [comment]
Hi Bjarne,

thanks for your help! now i've identified the issue and it is fixed in the master branch (3.6-beta1).

Enlighter now set's no-cache header via the WordPress buildin function `nocache_headers` to avoid browser caching on redirects as well set the http status code to **307** - this should avoid any similar issues in the future.

best regards, Andi
