### ISSUE TITLE
Line Numbers shown twice

### ISSUE THREAD

**Issue by ilmatte** [AndiDittrich/WordPress.Enlighter#92]
Hello I'm using Customizr theme and showing C# snippets with enlighter's block codes.
The line number is shown twice like at the following link:

http://theworkingdad.it/en/2017/12/28/string-representation-of-c-enum/

Can you help?

Regards,

Matteo

**Comment by AndiDittrich** [comment]
Hi Matteo,

you have some page styles set like `.czr-wp-the-content ol>li:before, ol>li:before` which are injecting pseudo-elements into the Enlighter lists.

just remove them or use more selective css rules 

best regards, Andi

**screenshot**

![ejs](https://user-images.githubusercontent.com/1474107/34655017-081a694c-f404-11e7-8810-81ad4bd10e52.jpg)
