### ISSUE TITLE
RTF and Visual Assist support?

### ISSUE THREAD

**Issue by RobertTroughton** [AndiDittrich/WordPress.Enlighter#93]
Hey,

It could be great if we could copy-paste ready-coloured (RTF format) text from Visual Studio (with Visual Assist)?

Visual Studio and Visual Assist supports copying with RTF (this is actually the default option) - see here: https://docs.wholetomato.com/default.asp?W218

So, essentially, if I copy a block of code from Visual Studio, it will be pre-coloured when I paste into certain tools, such as Microsoft Word.

It would be great if, in Enlighter, I could select a dropdown for "RTF Formatted" and paste the code in in that format... or something like that?

Enlighter's highlighting is great, it definitely makes code segments look cleaner... however, because it doesn't have a full view of the codebase, it can't, of course, know the types of various elements within the code. So the highlighting looks "nice" - but it's not quite right..?

Robert

**Comment by AndiDittrich** [comment]
Hi Robert,

i'm sorry but this is not possible - it's not the way Enlighter works.

Just paste your code into the visual editor witout using Enlighter.

best regards, Andi
